### ISSUE TITLE
Feature Request: Support multi-segment binaries in IF_LOAD

### ISSUE THREAD

**Issue by daschewie** [Trinity-11/Kernel_FMX#3]
**Problem:**
The PGX file format has a limit of 64k binaries. Larger programs compiled with WDC816CC often use multiple segments and can't use PGX.

**Proposal:**
The WDC816CC linker supports a binary version of s-records/hex files that support multiple segments. Code has been contributed to https://github.com/pweingar/C256Mgr/blob/master/C256Mgr/wdc.py as an alternative to hex files.

I am proposing using this format with either a fixed starting location, or adding a 24/32 bit header with the starting location to the existing format.

**Comment by dwsJason** [comment]
I think a binary equivalent of a .hex file would be very useful also.

**Comment by daschewie** [comment]
I am closing this issue, since it was addressed with the PGZ format.
